version: 2
updates:
  # Enable version updates for mix
  - package-ecosystem: "mix"
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Allow up to 2 open pull requests for mix dependencies
    open-pull-requests-limit: 2

