name: Build and Test
on:
  workflow_dispatch:
  # Triggers the workflow on pull request events but only for the master branch
  pull_request:
    branches: # matches refs/heads/master
      - 'main'
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  license:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check License Header
        uses: apache/skywalking-eyes/header@v0.4.0
        with:
          mode: fix
      - name: Apply License Changes
        uses: EndBug/add-and-commit@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          author_name: License Bot
          author_email: license_bot@github.com
          message: 'Automatic application of license header'
  test:
    needs: license
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    name: Build and Create Coverage Report
    strategy:
      matrix:
        otp: ['25.0.4']
        elixir: ['1.14.1']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.13.4'
          otp-version: '24.3'
      - name: Restore dependencies cache
        uses: actions/cache@v3.3.1
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Install dependencies
        run: mix deps.get
      - name: Compile dependencies
        run: mix deps.compile
      - name: Build package
        run: mix hex.build
      - name: Generating XML
        run: mix coveralls.json
        # todo: remove after tests are added
        continue-on-error: true
        env:
          MIX_ENV: test
          DB_HOSTNAME: postgres
          DB_NAME: test
          DB_USER: postgres
          DB_PASSWORD: postgres
      - name: Upload to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./cover/excoveralls.json
          directory: cover
          fail_ci_if_error: true
          verbose: true
