name: Test 🧪
on:
  workflow_dispatch:
  # Triggers the workflow on pull request events but only for the master branch
  pull_request:
    branches: # matches refs/heads/master
      - 'main'
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  MIX_ENV: test


jobs:
  test:
    runs-on: ubuntu-latest
    name: Create Coverage Report
    strategy:
      matrix:
        otp: ['25.0.4']
        elixir: ['1.14.1']
    steps:
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - uses: actions/checkout@v3
      - name: Get dependencies
        run: mix deps.get
      - name: Generating XML
        run: mix coveralls.json
        # todo: remove when tests are fixed
        continue-on-error: true
      - name: Upload to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./cover/excoveralls.json
          directory: cover
          fail_ci_if_error: true
          verbose: true

