name: Test 🧪
on:
  workflow_dispatch:
  # Triggers the workflow on pull request events but only for the master branch
  pull_request:
    branches: # matches refs/heads/master
      - 'main'
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    name: Create Coverage Report
    strategy:
      matrix:
        otp: ['25.0.4']
        elixir: ['1.14.1']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Get dependencies
        run: mix deps.get

      - name: Generating XML
        run: mix coveralls.json
        # todo: remove after tests are added
        continue-on-error: true
        env:
          MIX_ENV: test
          DB_HOSTNAME: postgres
          DB_NAME: test
          DB_USER: postgres
          DB_PASSWORD: postgres
      - name: Upload to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./cover/excoveralls.json
          directory: cover
          fail_ci_if_error: true
          verbose: true